"""Deterministic SVG comparison of Michell's 28-point scaffold.

The figure compares:

- Michell's approximate twenty-eight-point framework;
- the twelve Moon centres generated by that framework;
- the source-supported exact-incidence NJG_INC Moon centres;
- the small displacement between the two constructions.

The source SVG intentionally has a transparent background.
"""

from __future__ import annotations

from html import escape
from math import pi
from pathlib import Path

from .core_geometry import CoreDiagram
from .model_variants import ObliqueModel
from .oblique_geometry import build_oblique_placement
from .septenary_geometry import (
    MichellSeptenaryScaffold,
    ScaffoldRole,
    build_michell_28_point_scaffold,
    build_michell_gap_arithmetic,
)
from .septenary_verification import (
    verify_michell_28_point_scaffold,
)
from .wall_geometry import build_ordered_moon_circles


SVG_NAMESPACE = "http://www.w3.org/2000/svg"


def _format_number(value: float) -> str:
    """Return a compact deterministic decimal representation."""

    if abs(value) < 1.0e-15:
        return "0"

    return format(value, ".12g")


def _screen_point(
    x: float,
    y: float,
    *,
    centre_x: float,
    centre_y: float,
    scale: float,
) -> tuple[float, float]:
    """Convert mathematical coordinates to SVG screen coordinates."""

    return (
        centre_x + scale * x,
        centre_y - scale * y,
    )


def _role_marker(
    *,
    role: ScaffoldRole,
    index: int,
    x: float,
    y: float,
) -> str:
    """Return one SVG marker for a scaffold point."""

    role_name = role.value

    if role is ScaffoldRole.MOON_CENTRE:
        return (
            f'    <circle class="scaffold-marker moon-role" '
            f'data-scaffold-index="{index}" '
            f'data-role="{role_name}" '
            f'cx="{_format_number(x)}" '
            f'cy="{_format_number(y)}" '
            'r="0.115" />'
        )

    if role is ScaffoldRole.INTER_MOON_GAP:
        return (
            f'    <rect class="scaffold-marker gap-role" '
            f'data-scaffold-index="{index}" '
            f'data-role="{role_name}" '
            f'x="{_format_number(x - 0.105)}" '
            f'y="{_format_number(y - 0.105)}" '
            'width="0.21" height="0.21" />'
        )

    points = " ".join(
        (
            f"{_format_number(vertex_x)},"
            f"{_format_number(vertex_y)}"
        )
        for vertex_x, vertex_y in (
            (x, y + 0.14),
            (x + 0.14, y),
            (x, y - 0.14),
            (x - 0.14, y),
        )
    )

    return (
        f'    <polygon '
        f'class="scaffold-marker intersection-role" '
        f'data-scaffold-index="{index}" '
        f'data-role="{role_name}" '
        f'points="{points}" />'
    )


def michell_28_point_scaffold_to_svg(
    diagram: CoreDiagram,
    scaffold: MichellSeptenaryScaffold | None = None,
    *,
    canvas_width: int = 1400,
    canvas_height: int = 900,
    displacement_magnification: float = 40.0,
    title: str = "Michell approximate 28-point scaffold",
) -> str:
    """Return a deterministic SVG comparison with NJG_INC."""

    if canvas_width < 1200:
        raise ValueError(
            "Scaffold SVG width must be at least 1200 px."
        )

    if canvas_height < 750:
        raise ValueError(
            "Scaffold SVG height must be at least 750 px."
        )

    if displacement_magnification <= 0.0:
        raise ValueError(
            "displacement_magnification must be positive."
        )

    if scaffold is None:
        scaffold = build_michell_28_point_scaffold(
            diagram
        )

    report = verify_michell_28_point_scaffold(
        diagram,
        scaffold,
    )

    if not report.passed:
        raise ValueError(
            "Cannot render a scaffold that fails verification."
        )

    incidence_moons = build_ordered_moon_circles(
        diagram,
        ObliqueModel.INCIDENCE,
    )

    incidence_placement = build_oblique_placement(
        diagram,
        ObliqueModel.INCIDENCE,
    )

    scaffold_moons = scaffold.moon_centre_points
    gaps = build_michell_gap_arithmetic()

    plot_left = 28.0
    plot_width = 900.0
    information_left = 970.0
    information_width = (
        canvas_width - information_left - 28.0
    )

    centre_x = plot_left + plot_width / 2.0
    centre_y = canvas_height / 2.0 + 8.0

    geometry_extent = (
        diagram.construction_circle.radius
        + diagram.dimensions.moon_radius
        + 0.7
    )

    scale = min(
        (plot_width - 70.0) / (2.0 * geometry_extent),
        (canvas_height - 125.0)
        / (2.0 * geometry_extent),
    )

    square_half_side = diagram.earth_square.half_side

    exact_step_degrees = (
        report.exact_heptagon_step_radians
        * 180.0
        / pi
    )

    step_difference_degrees = (
        scaffold.heptagon_step_degrees
        - exact_step_degrees
    )

    incidence_beta_degrees = (
        report.incidence_beta_radians
        * 180.0
        / pi
    )

    beta_difference_degrees = (
        scaffold.beta_degrees
        - incidence_beta_degrees
    )

    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="{SVG_NAMESPACE}" '
            f'width="{canvas_width}" '
            f'height="{canvas_height}" '
            f'viewBox="0 0 {canvas_width} {canvas_height}" '
            'preserveAspectRatio="xMidYMid meet" '
            'role="img" '
            'shape-rendering="geometricPrecision">'
        ),
        f"  <title>{escape(title)}</title>",
        (
            "  <desc>"
            "Michell's approximate twenty-eight-point septenary "
            "framework compared with the exact-incidence placement "
            "of the twelve New Jerusalem Moon circles."
            "</desc>"
        ),
        "  <metadata>",
        "    Project: New Jerusalem Geometry",
        "    Source construction: How the World Is Made, Figure 194",
        "    Scaffold role classification: 12 + 8 + 8",
        "    Comparison model: NJG_INC",
        "    Background: transparent",
        "  </metadata>",
        "  <style>",
        "    text {",
        "      font-family: system-ui, sans-serif;",
        "      fill: #171717;",
        "    }",
        "    .title {",
        "      font-size: 25px;",
        "      font-weight: 600;",
        "      text-anchor: middle;",
        "    }",
        "    .subtitle {",
        "      font-size: 14px;",
        "      text-anchor: middle;",
        "      fill: #555555;",
        "    }",
        "    .geometry {",
        "      fill: none;",
        "      vector-effect: non-scaling-stroke;",
        "      stroke-linecap: round;",
        "      stroke-linejoin: round;",
        "    }",
        "    .construction-circle {",
        "      stroke: #777777;",
        "      stroke-width: 1.25;",
        "    }",
        "    .earth-square {",
        "      stroke: #3e3e3e;",
        "      stroke-width: 1.35;",
        "    }",
        "    .earth-circle {",
        "      stroke: #111111;",
        "      stroke-width: 1.8;",
        "    }",
        "    .scaffold-ray {",
        "      stroke: #b3b3b3;",
        "      stroke-width: 0.75;",
        "      opacity: 0.56;",
        "    }",
        "    .incidence-moon {",
        "      stroke: #686868;",
        "      stroke-width: 1.15;",
        "      fill: none;",
        "      opacity: 0.7;",
        "    }",
        "    .scaffold-moon {",
        "      stroke: #1769aa;",
        "      stroke-width: 1.35;",
        "      stroke-dasharray: 4 3;",
        "      fill: none;",
        "      opacity: 0.9;",
        "    }",
        "    .displacement {",
        "      stroke: #b24b18;",
        "      stroke-width: 1.8;",
        "    }",
        "    .incidence-centre-mark {",
        "      stroke: #111111;",
        "      stroke-width: 1.25;",
        "    }",
        "    .square-circle-point {",
        "      fill: #111111;",
        "      stroke: none;",
        "    }",
        "    .scaffold-marker {",
        "      vector-effect: non-scaling-stroke;",
        "      stroke-width: 1;",
        "    }",
        "    .moon-role {",
        "      fill: #1769aa;",
        "      stroke: #ffffff;",
        "    }",
        "    .gap-role {",
        "      fill: #b45f06;",
        "      stroke: #ffffff;",
        "    }",
        "    .intersection-role {",
        "      fill: #6a3d9a;",
        "      stroke: #ffffff;",
        "    }",
        "    .panel-rule {",
        "      stroke: #d0d0d0;",
        "      stroke-width: 1;",
        "    }",
        "    .panel-heading {",
        "      font-size: 17px;",
        "      font-weight: 600;",
        "    }",
        "    .metric-label {",
        "      font-size: 13px;",
        "      fill: #555555;",
        "    }",
        "    .metric-value {",
        "      font-size: 14px;",
        "      font-weight: 600;",
        "    }",
        "    .note {",
        "      font-size: 12px;",
        "      fill: #555555;",
        "    }",
        "    .legend-text {",
        "      font-size: 12px;",
        "    }",
        "    .inset-frame {",
        "      fill: none;",
        "      stroke: #c8c8c8;",
        "      stroke-width: 1;",
        "    }",
        "    .inset-origin {",
        "      fill: #1769aa;",
        "      stroke: none;",
        "    }",
        "    .inset-target {",
        "      fill: #111111;",
        "      stroke: none;",
        "    }",
        "    .inset-vector {",
        "      stroke: #b24b18;",
        "      stroke-width: 2;",
        "    }",
        "    .status-box {",
        "      fill: #f4f7fa;",
        "      fill-opacity: 0.75;",
        "      stroke: #cad4de;",
        "      stroke-width: 1;",
        "    }",
        "  </style>",
        (
            f'  <text class="title" '
            f'x="{canvas_width / 2:.6g}" y="31">'
            f"{escape(title)}</text>"
        ),
        (
            f'  <text class="subtitle" '
            f'x="{canvas_width / 2:.6g}" y="53">'
            "Approximate septenary framework compared with "
            "source-supported exact incidence"
            "</text>"
        ),
        (
            f'  <line class="panel-rule" '
            f'x1="{information_left - 20:.6g}" y1="72" '
            f'x2="{information_left - 20:.6g}" '
            f'y2="{canvas_height - 28}" />'
        ),
        (
            f'  <g id="scaffold-geometry" '
            f'transform="translate('
            f'{_format_number(centre_x)} '
            f'{_format_number(centre_y)}) '
            f'scale({_format_number(scale)},'
            f'-{_format_number(scale)})">'
        ),
    ]

    for point in scaffold.points:
        lines.append(
            (
                '    <line class="geometry scaffold-ray" '
                'x1="0" y1="0" '
                f'x2="{_format_number(point.point.x)}" '
                f'y2="{_format_number(point.point.y)}" />'
            )
        )

    lines.extend(
        [
            (
                '    <circle '
                'class="geometry construction-circle" '
                f'cx="{_format_number(diagram.construction_circle.centre.x)}" '
                f'cy="{_format_number(diagram.construction_circle.centre.y)}" '
                f'r="{_format_number(diagram.construction_circle.radius)}" />'
            ),
            (
                '    <rect class="geometry earth-square" '
                f'x="{_format_number(-square_half_side)}" '
                f'y="{_format_number(-square_half_side)}" '
                f'width="{_format_number(diagram.earth_square.side)}" '
                f'height="{_format_number(diagram.earth_square.side)}" />'
            ),
            (
                '    <circle class="geometry earth-circle" '
                f'cx="{_format_number(diagram.earth_circle.centre.x)}" '
                f'cy="{_format_number(diagram.earth_circle.centre.y)}" '
                f'r="{_format_number(diagram.earth_circle.radius)}" />'
            ),
        ]
    )

    for index, (_, moon) in enumerate(incidence_moons):
        lines.append(
            (
                f'    <circle '
                f'id="incidence-moon-{index:02d}" '
                'class="geometry incidence-moon" '
                f'cx="{_format_number(moon.centre.x)}" '
                f'cy="{_format_number(moon.centre.y)}" '
                f'r="{_format_number(moon.radius)}" />'
            )
        )

    for index, point in enumerate(scaffold_moons):
        lines.append(
            (
                f'    <circle '
                f'id="scaffold-moon-{index:02d}" '
                'class="geometry scaffold-moon" '
                f'cx="{_format_number(point.point.x)}" '
                f'cy="{_format_number(point.point.y)}" '
                f'r="{_format_number(diagram.dimensions.moon_radius)}" />'
            )
        )

    for index, (
        scaffold_point,
        (_, incidence_moon),
    ) in enumerate(
        zip(
            scaffold_moons,
            incidence_moons,
            strict=True,
        )
    ):
        centre = incidence_moon.centre
        half_cross = 0.095

        lines.extend(
            [
                (
                    f'    <line class="geometry displacement" '
                    f'data-displacement-index="{index}" '
                    f'x1="{_format_number(scaffold_point.point.x)}" '
                    f'y1="{_format_number(scaffold_point.point.y)}" '
                    f'x2="{_format_number(centre.x)}" '
                    f'y2="{_format_number(centre.y)}" />'
                ),
                (
                    '    <line '
                    'class="geometry incidence-centre-mark" '
                    f'x1="{_format_number(centre.x - half_cross)}" '
                    f'y1="{_format_number(centre.y)}" '
                    f'x2="{_format_number(centre.x + half_cross)}" '
                    f'y2="{_format_number(centre.y)}" />'
                ),
                (
                    '    <line '
                    'class="geometry incidence-centre-mark" '
                    f'x1="{_format_number(centre.x)}" '
                    f'y1="{_format_number(centre.y - half_cross)}" '
                    f'x2="{_format_number(centre.x)}" '
                    f'y2="{_format_number(centre.y + half_cross)}" />'
                ),
            ]
        )

    for moon in incidence_placement.moons:
        target = moon.target_intersection.point

        lines.append(
            (
                '    <circle class="square-circle-point" '
                f'cx="{_format_number(target.x)}" '
                f'cy="{_format_number(target.y)}" '
                'r="0.075" />'
            )
        )

    for point in scaffold.points:
        lines.append(
            _role_marker(
                role=point.role,
                index=point.index,
                x=point.point.x,
                y=point.point.y,
            )
        )

    lines.append("  </g>")

    legend_y = canvas_height - 42.0

    lines.extend(
        [
            '  <g id="role-legend">',
            (
                f'    <circle class="moon-role" '
                f'cx="{plot_left + 20:.6g}" '
                f'cy="{legend_y:.6g}" r="5" />'
            ),
            (
                f'    <text class="legend-text" '
                f'x="{plot_left + 32:.6g}" '
                f'y="{legend_y + 4:.6g}">'
                "12 Moon-centre points</text>"
            ),
            (
                f'    <rect class="gap-role" '
                f'x="{plot_left + 192:.6g}" '
                f'y="{legend_y - 5:.6g}" '
                'width="10" height="10" />'
            ),
            (
                f'    <text class="legend-text" '
                f'x="{plot_left + 210:.6g}" '
                f'y="{legend_y + 4:.6g}">'
                "8 inter-Moon gaps</text>"
            ),
            (
                f'    <polygon class="intersection-role" '
                f'points="'
                f'{plot_left + 385:.6g},{legend_y - 6:.6g} '
                f'{plot_left + 391:.6g},{legend_y:.6g} '
                f'{plot_left + 385:.6g},{legend_y + 6:.6g} '
                f'{plot_left + 379:.6g},{legend_y:.6g}" />'
            ),
            (
                f'    <text class="legend-text" '
                f'x="{plot_left + 400:.6g}" '
                f'y="{legend_y + 4:.6g}">'
                "8 intersection positioners</text>"
            ),
            (
                f'    <line class="displacement" '
                f'x1="{plot_left + 630:.6g}" '
                f'y1="{legend_y:.6g}" '
                f'x2="{plot_left + 650:.6g}" '
                f'y2="{legend_y:.6g}" />'
            ),
            (
                f'    <text class="legend-text" '
                f'x="{plot_left + 660:.6g}" '
                f'y="{legend_y + 4:.6g}">'
                "scaffold → NJG_INC</text>"
            ),
            "  </g>",
        ]
    )

    panel_x = information_left

    lines.extend(
        [
            (
                f'  <g id="information-panel" '
                f'transform="translate('
                f'{_format_number(panel_x)} 91)">'
            ),
            '    <text class="panel-heading" x="0" y="0">'
            "Septenary approximation</text>",
            '    <text class="metric-label" x="0" y="31">'
            "Michell step α</text>",
            (
                '    <text class="metric-value" x="0" y="51">'
                f"{scaffold.heptagon_step_degrees:.12f}°"
                "</text>"
            ),
            '    <text class="metric-label" x="0" y="80">'
            "Exact 360°/7 step</text>",
            (
                '    <text class="metric-value" x="0" y="100">'
                f"{exact_step_degrees:.12f}°"
                "</text>"
            ),
            '    <text class="metric-label" x="0" y="129">'
            "Difference</text>",
            (
                '    <text class="metric-value" x="0" y="149">'
                f"{step_difference_degrees:+.12f}°"
                "</text>"
            ),
            (
                '    <text class="metric-value" x="0" y="174">'
                f"Relative error: "
                f"{100.0 * report.relative_heptagon_step_error:.9f}%"
                "</text>"
            ),
            (
                f'    <line class="panel-rule" '
                f'x1="0" y1="199" '
                f'x2="{_format_number(information_width)}" '
                'y2="199" />'
            ),
            '    <text class="panel-heading" x="0" y="231">'
            "Moon-centre comparison</text>",
            '    <text class="metric-label" x="0" y="262">'
            "Scaffold β</text>",
            (
                '    <text class="metric-value" x="0" y="282">'
                f"{scaffold.beta_degrees:.12f}°"
                "</text>"
            ),
            '    <text class="metric-label" x="0" y="311">'
            "NJG_INC β</text>",
            (
                '    <text class="metric-value" x="0" y="331">'
                f"{incidence_beta_degrees:.12f}°"
                "</text>"
            ),
            '    <text class="metric-label" x="0" y="360">'
            "Angular difference</text>",
            (
                '    <text class="metric-value" x="0" y="380">'
                f"{beta_difference_degrees:+.12f}°"
                "</text>"
            ),
            '    <text class="metric-label" x="0" y="409">'
            "Maximum centre displacement</text>",
            (
                '    <text class="metric-value" x="0" y="429">'
                f"{report.maximum_centre_displacement:.12f} u"
                "</text>"
            ),
            '    <text class="metric-label" x="0" y="458">'
            "Incidence residual</text>",
            (
                '    <text class="metric-value" x="0" y="478">'
                f"{report.scaffold_incidence_residual:.12f} u"
                "</text>"
            ),
            (
                f'    <line class="panel-rule" '
                f'x1="0" y1="503" '
                f'x2="{_format_number(information_width)}" '
                'y2="503" />'
            ),
            '    <text class="panel-heading" x="0" y="535">'
            "Figure 28 arithmetic</text>",
            (
                '    <text class="metric-value" x="0" y="566">'
                f"{gaps.moon_total:.0f} + "
                f"{gaps.large_gap_total:.6f} + "
                f"{gaps.small_gap_total:.6f} = "
                f"{gaps.total:.0f}"
                "</text>"
            ),
            '    <text class="note" x="0" y="590">'
            "12 Moon diameters + 4 large gaps</text>",
            '    <text class="note" x="0" y="609">'
            "+ 8 small gaps</text>",
            "  </g>",
        ]
    )

    example_scaffold = scaffold_moons[1].point
    example_incidence = incidence_moons[1][1].centre

    inset_start_x = (
        information_left + information_width - 32.0
    )
    inset_start_y = 785.0

    inset_end_x = (
        inset_start_x
        + (
            example_incidence.x
            - example_scaffold.x
        )
        * scale
        * displacement_magnification
    )

    inset_end_y = (
        inset_start_y
        - (
            example_incidence.y
            - example_scaffold.y
        )
        * scale
        * displacement_magnification
    )

    lines.extend(
        [
            (
                f'  <g id="displacement-inset" '
                f'data-magnification="'
                f'{_format_number(displacement_magnification)}">'
            ),
            (
                f'    <rect class="inset-frame" '
                f'x="{information_left:.6g}" y="710" '
                f'width="{information_width:.6g}" '
                'height="90" rx="7" />'
            ),
            (
                f'    <text class="panel-heading" '
                f'x="{information_left + 14:.6g}" y="733">'
                "Oblique displacement inset</text>"
            ),
            (
                f'    <text class="note" '
                f'x="{information_left + 14:.6g}" y="753">'
                f"One centre shift magnified "
                f"{displacement_magnification:g}×"
                "</text>"
            ),
            (
                f'    <line class="inset-vector" '
                f'x1="{_format_number(inset_start_x)}" '
                f'y1="{_format_number(inset_start_y)}" '
                f'x2="{_format_number(inset_end_x)}" '
                f'y2="{_format_number(inset_end_y)}" />'
            ),
            (
                f'    <circle class="inset-origin" '
                f'cx="{_format_number(inset_start_x)}" '
                f'cy="{_format_number(inset_start_y)}" '
                'r="5" />'
            ),
            (
                f'    <circle class="inset-target" '
                f'cx="{_format_number(inset_end_x)}" '
                f'cy="{_format_number(inset_end_y)}" '
                'r="5" />'
            ),
            (
                f'    <text class="note" '
                f'x="{information_left + 14:.6g}" y="783">'
                "blue = scaffold; black = NJG_INC"
                "</text>"
            ),
            "  </g>",
            (
                f'  <rect class="status-box" '
                f'x="{information_left:.6g}" y="815" '
                f'width="{information_width:.6g}" '
                'height="56" rx="7" />'
            ),
            (
                f'  <text class="note" '
                f'x="{information_left + 13:.6g}" y="838">'
                "Angular scaffold: approximate."
                "</text>"
            ),
            (
                f'  <text class="note" '
                f'x="{information_left + 13:.6g}" y="858">'
                "Circumference arithmetic: exact under π = 22/7."
                "</text>"
            ),
            "</svg>",
            "",
        ]
    )

    return "\n".join(lines)


def write_michell_28_point_scaffold_svg(
    diagram: CoreDiagram,
    output_path: str | Path,
    scaffold: MichellSeptenaryScaffold | None = None,
    *,
    canvas_width: int = 1400,
    canvas_height: int = 900,
    displacement_magnification: float = 40.0,
) -> Path:
    """Write the deterministic scaffold comparison SVG."""

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    path.write_text(
        michell_28_point_scaffold_to_svg(
            diagram,
            scaffold,
            canvas_width=canvas_width,
            canvas_height=canvas_height,
            displacement_magnification=(
                displacement_magnification
            ),
        ),
        encoding="utf-8",
    )

    return path
